import {lessons} from './lessons.js';
import {tracks,sources,questions,pool,score} from './data.js';
const $=s=>document.querySelector(s),app=$('#app');
let saved={track:'ICAO',attempts:[],wrong:[],read:[]},storageOK=true;
try{const x=JSON.parse(localStorage.getItem('flightdeck.v1'));if(x&&tracks.some(t=>t.id===x.track)&&Array.isArray(x.attempts)&&Array.isArray(x.wrong)){saved={read:Array.isArray(x.read)?x.read.filter(id=>lessons.some(l=>l.id===id)):[],track:x.track,attempts:x.attempts.filter(a=>a&&questions.some(q=>q.id===a.id)&&typeof a.correct==='boolean'),wrong:x.wrong.filter(id=>questions.some(q=>q.id===id))};}}catch{storageOK=false;}
let subject='all',query='',session=null,clock=null;
const persist=()=>{try{localStorage.setItem('flightdeck.v1',JSON.stringify(saved));}catch{storageOK=false;}$('#wrong-badge').textContent=saved.wrong.length;};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const track=()=>tracks.find(t=>t.id===saved.track);
const titles={home:'學習總覽',learn:'學習教室',practice:'主題題庫',exam:'模擬考試',mistakes:'我的錯題本',sources:'參考資料庫'};
function sourceHTML(q){const s=sources[q.source];return `<div class="muted">${esc(q.term)}<br>參考：<a href="${s.url}" target="_blank" rel="noopener noreferrer">${s.title} ↗</a><br>${s.section} · ${s.version}<br>示範題整理日期：${q.reviewed} · ${q.effective}</div>`;}
function heading(title,description){return `<div class="heading"><div><div class="eyebrow">YOUR NEXT CHAPTER IN AVIATION</div><h1>${title}</h1><p class="muted">${description}</p></div><span class="date-pill">✦ &nbsp; ${track().label}</span></div>`;}
function home(){const count=new Set(saved.attempts.map(a=>a.id)).size,correct=saved.attempts.filter(a=>a.correct).length;app.innerHTML=heading('準備好，向下一個高度出發。','把每一次練習，變成更有把握的飛行。')+`<section class="hero"><div class="hero-copy"><div class="eyebrow">YOUR JOURNEY TO THE FLIGHT DECK</div><h2>從地面知識，<br>到天空中的每一個決定。</h2><p>四大學習體系・繁中解析・英文航空術語<br>依照你的步調，建立扎實的機師知識。</p><button class="button light" data-action="learn">開始閱讀教材 <span>↗</span></button></div><div class="hero-art" aria-hidden="true"><div class="ring"></div><div class="ring r2"></div><div class="ring r3"></div><div class="axis"></div><div class="plane">✈</div><span class="art-label">N 25° 04′<br>──────────<br>FLIGHT PLAN / 001</span><span class="coordinate">KNOWLEDGE → CONFIDENCE</span></div></section><section class="stats"><div class="stat"><span class="stat-label">已練習題目</span><strong>${count}<small> / ${questions.length}</small></strong><small>一步一步，累積飛行知識</small></div><div class="stat"><span class="stat-label">累計答題正確率</span><strong>${saved.attempts.length?Math.round(correct/saved.attempts.length*100)+'%':'—'}</strong><small>${saved.attempts.length?'依所有已提交答案計算':'完成第一次練習後顯示'}</small></div><div class="stat"><span class="stat-label">待複習錯題</span><strong>${saved.wrong.length}<small> 題</small></strong><small>理解錯誤，就是進步的開始</small></div><div class="stat"><span class="stat-label">目前學習體系</span><strong style="font-size:23px">${saved.track==='TW'?'CAA':saved.track}</strong><small>可隨時切換你的學習路徑</small></div></section><div class="section-heading"><h2>選擇你的學習航線</h2><span>04 LEARNING PATHS</span></div><section class="track-grid">${tracks.map(t=>`<button class="track-card ${t.color} ${saved.track===t.id?'selected':''}" data-track="${t.id}" aria-pressed="${saved.track===t.id}"><div class="track-top"><span class="track-mark">${t.mark}</span>${saved.track===t.id?'<span class="selected-label">● 目前學習</span>':'<span class="muted">↗</span>'}</div><h3>${t.name}</h3><div class="en">${t.label}</div><p>${t.description}</p><div class="track-meta"><span>${pool(t.id).length} 道入門示範題</span><span>探索航線 →</span></div></button>`).join('')}</section><section class="lower-grid"><div><div class="section-heading"><h2>從一個主題開始</h2><span>BUILD YOUR FOUNDATION</span></div><div class="panel">${['航空法規','飛行原理','導航','人因'].map((s,i)=>`<div class="subject-row"><span class="subject-icon">${['§','✈','⌖','◎'][i]}</span><div class="subject-info"><b>${s}</b><small>${['AIR LAW','PRINCIPLES OF FLIGHT','NAVIGATION','HUMAN PERFORMANCE'][i]} · ${pool(saved.track,s).length} 道題目</small></div><button class="text-button" data-subject="${s}">開始練習 →</button></div>`).join('')}</div></div><div><div class="section-heading"><h2>準備一次小型檢核</h2><span>PRACTICE CHECK</span></div><div class="panel"><span class="tag">基礎混合練習</span><h3 style="margin-top:20px">把理解，變成答題的信心。</h3><p class="muted">隨機抽取最多 5 題，在 5 分鐘內完成。交卷後查看每題解析與參考來源。</p><button class="button secondary" data-action="exam-page">進入模擬考 →</button></div></div></section>`;}
function filters(){return `<div class="filters"><select id="track-filter" aria-label="學習體系">${tracks.map(t=>`<option value="${t.id}" ${saved.track===t.id?'selected':''}>${t.name}</option>`).join('')}</select><select id="subject-filter" aria-label="學習主題"><option value="all">所有主題</option>${[...new Set(questions.map(q=>q.subject))].map(s=>`<option ${subject===s?'selected':''}>${s}</option>`).join('')}</select><input id="search" aria-label="搜尋題目或英文術語" placeholder="搜尋題目、英文術語…" value="${esc(query)}"></div>`;}
function list(wrong=false){app.innerHTML=heading(wrong?'把錯題，變成下一次的把握。':'你的知識，從這一題開始。',wrong?'跨體系錯題集中整理；答對後自動移出待複習清單。':'各體系包含共通基礎題；地方制度題另行標示，皆為入門自編示範。')+(wrong?'':filters())+`<div id="question-results"></div>`;drawList(wrong);}
function drawList(wrong=false){const items=wrong?questions.filter(q=>saved.wrong.includes(q.id)):pool(saved.track,subject).filter(q=>(q.title+q.term).toLowerCase().includes(query.toLowerCase()));$('#question-results').innerHTML=items.length?`<div class="section-heading"><span>共 ${items.length} 題 · 自編示範教材</span><button class="button secondary" data-action="${wrong?'review':'filtered'}">${wrong?'重練所有錯題':'練習篩選題目'} →</button></div><div class="question-list">${items.map(q=>`<article class="question-card"><div><span class="tag">${q.track==='ICAO'?'共通基礎':q.track}</span><span class="tag">${q.subject}</span><h3>${q.title}</h3><p class="muted">${q.term}</p></div><button class="button secondary" data-question="${q.id}">練習 →</button></article>`).join('')}</div>`:`<div class="empty"><div class="symbol">${wrong?'✓':'⌕'}</div><h2>${wrong?'目前沒有待複習錯題':'沒有符合的題目'}</h2><p class="muted">${wrong?'開始一次練習，系統會自動記錄需要加強的題目。':'試試其他主題或關鍵字。'}</p><button class="button" data-action="start">開始練習 →</button></div>`;}
function examPage(){app.innerHTML=heading('給自己一次起飛前的檢核。','短時間集中練習，確認你真正理解的知識。')+filters()+`<section class="panel quiz"><div class="eyebrow">MOCK EXAM / DEMO</div><h2>${track().name} · 基礎模擬考</h2><p class="muted">依目前體系與主題隨機抽取最多 5 題，共 5 分鐘。答案可在交卷前修改；時間到自動交卷，未答題以錯誤計。</p><div class="callout">這是本站的示範測驗設定，不代表任何主管機關的正式考試題數、時限或及格標準。第一版尚未提供 PPL／CPL／ATPL 完整專業題庫。</div><p class="muted">目前可用：${pool(saved.track,subject).length} 題</p><button class="button" data-action="begin-exam">開始計時測驗 →</button></section>`;$('#search').remove();}
function sourcePage(){app.innerHTML=heading('好的學習，從可靠的來源開始。','查閱官方入口，並核對文件版本與適用範圍。')+`<div class="callout">示範題整理日期：2026-09-06。入口網頁查核不代表所有條文均完成專業審校；未標示日期的文件不推定生效日。各地規範不可互相替代。</div>`+Object.values(sources).map(s=>`<article class="source-card"><h3>${s.title}</h3><p class="muted">${s.section}<br>版本／生效資訊：${s.version}</p><a href="${s.url}" target="_blank" rel="noopener noreferrer">開啟官方參考資料 ↗</a></article>`).join('');}
function render(){const route=location.hash.slice(1)||'home';const view=route.startsWith('lesson/')?'learn':route;if(session&&!session.done)return;document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.view===view));$('#page-name').textContent=titles[view]||titles.home;persist();if(route.startsWith('lesson/'))lessonPage(route.slice(7));else if(view==='learn')learningPage();else if(view==='practice')list();else if(view==='mistakes')list(true);else if(view==='exam')examPage();else if(view==='sources')sourcePage();else home();if(!storageOK)app.insertAdjacentHTML('afterbegin','<p class="storage-warning">瀏覽器無法儲存紀錄；本次練習仍可使用，但關閉頁面後可能遺失。</p>');}
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function start(items,mode='practice'){if(!items.length)return;session={items:mode==='exam'?shuffle(items).slice(0,5):items,mode,index:0,answers:{},committed:new Set(),done:false,deadline:Date.now()+300000};clearInterval(clock);if(mode==='exam')clock=setInterval(()=>{if(Date.now()>=session.deadline)finish();else if($('#timer'))$('#timer').textContent=time();},500);quiz();window.scrollTo(0,0);}
function time(){const sec=Math.max(0,Math.ceil((session.deadline-Date.now())/1000));return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;}
function record(q,answer){saved.attempts.push({id:q.id,correct:answer===q.answer,date:new Date().toISOString()});saved.wrong=saved.wrong.filter(id=>id!==q.id);if(answer!==q.answer)saved.wrong.push(q.id);persist();}
function quiz(){const s=session,q=s.items[s.index],committed=s.committed.has(q.id),selected=s.answers[q.id];app.innerHTML=`<section class="quiz"><div class="quiz-top"><button class="text-button" data-action="exit">← 結束${s.mode==='exam'?'並交卷':'練習'}</button><span class="muted">${s.mode==='exam'?'<span id="timer" class="timer">'+time()+'</span> 剩餘 · ':''}${s.index+1} / ${s.items.length}</span></div><div class="progress"><div style="width:${(s.index+1)/s.items.length*100}%"></div></div><article class="panel"><span class="tag">${q.track==='ICAO'?'共通基礎':q.track}</span><span class="tag">${q.subject}</span><span class="tag">${q.kind}</span><h2>${q.title}</h2><div class="options">${q.options.map((o,i)=>`<button class="option ${selected===i?'selected':''} ${committed&&i===q.answer?'correct':''} ${committed&&selected===i&&i!==q.answer?'wrong':''}" data-answer="${i}" ${committed?'disabled':''} aria-pressed="${selected===i}"><b>${String.fromCharCode(65+i)}</b>${o}</button>`).join('')}</div>${committed?`<div class="explanation" role="status"><b>${selected===q.answer?'✓ 答對了':'再理解一次'} · 正確答案 ${String.fromCharCode(65+q.answer)}</b><p>${q.explanation}</p>${sourceHTML(q)}</div>`:''}<div class="quiz-actions"><button class="button secondary" data-action="previous" ${s.index===0?'disabled':''}>← 上一題</button>${s.mode==='practice'&&!committed?`<button class="button" data-action="check" ${selected===undefined?'disabled':''}>確認答案 →</button>`:`<button class="button" data-action="next">${s.index===s.items.length-1?(s.mode==='exam'?'交卷並看結果':'查看練習結果'):'下一題 →'}</button>`}</div></article></section>`;}
function finish(){clearInterval(clock);const s=session;if(!s||s.done)return;s.done=true;if(s.mode==='exam')s.items.forEach(q=>record(q,s.answers[q.id]));const items=s.mode==='exam'?s.items:s.items.filter(q=>s.committed.has(q.id));const correct=score(items,s.answers);app.innerHTML=`<section class="quiz"><div class="empty"><div class="eyebrow">SESSION COMPLETE</div><h1>每次練習，都是向前一步。</h1><div class="result-number">${correct}<small> / ${items.length}</small></div><p class="muted">${items.length?'正確率 '+Math.round(correct/items.length*100)+'% · 錯題已加入複習清單':'尚未提交答案，本次沒有新增紀錄'}<br>這是示範練習結果，不代表證照考試資格或能力認證。</p><button class="button" data-action="home">回到學習總覽 →</button> <button class="button secondary" data-action="mistakes">查看錯題本</button></div>${items.length?'<div class="section-heading"><h2>逐題回顧</h2></div><div class="panel">'+items.map(q=>`<div class="review-row"><span class="tag">${s.answers[q.id]===q.answer?'✓ 正確':'需複習'}</span><h3>${q.title}</h3><p>你的答案：${esc(q.options[s.answers[q.id]]??'未作答')}<br>正確答案：${q.options[q.answer]}</p><details><summary>閱讀解析與来源</summary><p>${q.explanation}</p>${sourceHTML(q)}</details></div>`).join('')+'</div>':''}</section>`;window.scrollTo(0,0);}
function go(view){clearInterval(clock);session=null;if(location.hash==='#'+view)render();else location.hash=view;}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.lesson){go('lesson/'+b.dataset.lesson);return;}if(b.dataset.read){saved.read=saved.read.includes(b.dataset.read)?saved.read.filter(id=>id!==b.dataset.read):[...saved.read,b.dataset.read];persist();lessonPage(b.dataset.read);return;}if(b.dataset.lessonQuiz){const l=lessons.find(l=>l.id===b.dataset.lessonQuiz);start(questions.filter(q=>l.questionIds.includes(q.id)));return;}if(b.dataset.section){document.getElementById(b.dataset.section)?.scrollIntoView({behavior:'smooth'});return;}if(b.dataset.track){saved.track=b.dataset.track;subject='all';persist();home();return;}if(b.dataset.subject){subject=b.dataset.subject;query='';start(pool(saved.track,subject));return;}if(b.dataset.question){start([questions.find(q=>q.id===b.dataset.question)]);return;}if(b.dataset.answer!==undefined){const q=session.items[session.index];if(!session.committed.has(q.id)){session.answers[q.id]=Number(b.dataset.answer);quiz();}return;}switch(b.dataset.action){case 'learn':go('learn');break;case 'start':start(pool(saved.track));break;case 'filtered':start(pool(saved.track,subject).filter(q=>(q.title+q.term).toLowerCase().includes(query.toLowerCase())));break;case 'review':start(questions.filter(q=>saved.wrong.includes(q.id)));break;case 'exam-page':go('exam');break;case 'begin-exam':start(pool(saved.track,subject),'exam');break;case 'check':{const q=session.items[session.index];if(session.answers[q.id]===undefined||session.committed.has(q.id))break;record(q,session.answers[q.id]);session.committed.add(q.id);quiz();break;}case 'previous':if(session.index>0){session.index--;quiz();}break;case 'next':if(session.index<session.items.length-1){session.index++;quiz();}else finish();break;case 'exit':finish();break;case 'home':go('home');break;case 'mistakes':go('mistakes');break;}});
app.addEventListener('change',e=>{if(e.target.id==='track-filter'){saved.track=e.target.value;persist();render();}if(e.target.id==='subject-filter'){subject=e.target.value;render();}});
app.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;drawList();}});
window.addEventListener('hashchange',()=>{if(session&&!session.done){if(session.mode==='exam'){finish();return;}clearInterval(clock);session=null;}render();});
window.addEventListener('beforeunload',e=>{if(session&&!session.done&&session.mode==='exam'){e.preventDefault();e.returnValue='';}});
render();

function lessonCards(items){return items.map(l=>`<article class="lesson-card"><div><span class="tag">${l.track==='COMMON'?'共通基礎':l.track}</span><span class="tag">${l.subject}</span><span class="read-status">${saved.read.includes(l.id)?'✓ 已讀':''}</span></div><h2>${l.title}</h2><p class="muted">${l.summary}</p>${l.objectives?'<p class="lesson-features">學習目標 · 例題 · 誤解辨析 · 自我檢核</p>':''}<div class="lesson-meta"><span>${l.minutes} 分鐘 · ${l.refs.length} 個官方來源</span><button class="text-button" data-lesson="${l.id}">閱讀教材 →</button></div></article>`).join('');}
function learningPage(){app.innerHTML=heading('先理解，再練習。','閱讀完整入門文章，從概念、例題到官方出處，建立自己的知識脈絡。')+`<div class="reading-banner"><div><div class="eyebrow">GROUND SCHOOL / READING ROOM</div><h2>從飛行原理，到讀懂天氣電報</h2><p>已讀 ${saved.read.length} / ${lessons.length} 篇 · 閱讀進度保存在此裝置</p></div><span class="reading-symbol" aria-hidden="true">▤</span></div><div class="filters"><select id="lesson-track" aria-label="文章適用體系"><option value="all">所有體系</option><option value="COMMON">共通基礎</option>${tracks.map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}</select><select id="lesson-subject" aria-label="文章主題"><option value="all">所有主題</option>${[...new Set(lessons.map(l=>l.subject))].map(subject=>`<option value="${subject}">${subject}</option>`).join('')}</select><input id="lesson-search" aria-label="搜尋教材" placeholder="搜尋教材、主題或英文術語…"></div><div class="learning-route"><b>建議入門順序</b><span>飛行原理 → 飛行操縱 → 儀表 → 重量與性能 → 航空氣象 → 導航與機場 → 各地制度</span><p>依主題逐步閱讀；已讀表示完成閱讀，不代表已通過能力評量。</p></div><p id="lesson-count" class="muted">共 ${lessons.length} 篇教材</p><div id="lesson-grid" class="lesson-grid">${lessonCards(lessons)}</div><p class="muted">內容為本站繁中改寫與自編例子，非官方翻譯。共通文章使用 FAA 教材說明原理；各地制度文章另標適用範圍。</p>`;}
function lessonPage(id){const l=lessons.find(l=>l.id===id);if(!l){app.innerHTML='<div class="empty"><h1>找不到這篇文章</h1><button class="button" data-action="learn">返回學習教室</button></div>';return;}app.innerHTML=`<button class="text-button" data-action="learn">← 返回學習教室</button><div class="article-layout"><aside class="article-toc"><div class="eyebrow">IN THIS LESSON</div>${l.sections.map((s,i)=>`<button class="text-button" data-section="section-${i}">${String(i+1).padStart(2,'0')} ${s.title}</button>`).join('')}<button class="text-button" data-section="lesson-sources">官方來源與版本</button></aside><article class="article-body"><span class="tag">${l.track==='COMMON'?'共通基礎':l.track}</span><span class="tag">${l.subject}</span><h1>${l.title}</h1><p class="article-deck">${l.summary}</p><div class="article-byline">FLIGHTDECK 編寫 · 約 ${l.minutes} 分鐘 · 整理日期 2026-09-06</div>${l.objectives?`<section class="learning-goals"><div class="eyebrow">AFTER THIS LESSON</div><h2>這一課，你會學到</h2><ul>${l.objectives.map(g=>`<li>${g}</li>`).join('')}</ul><p class="muted">${l.prerequisite}</p></section>`:''}<div class="terms">${l.terms.map(t=>`<span>${t}</span>`).join('')}</div>${l.sections.map((s,i)=>`<section id="section-${i}"><h2><small>${String(i+1).padStart(2,'0')}</small>${s.title}</h2><p>${s.text}</p><a class="inline-source" href="${l.refs[s.ref].url}" target="_blank" rel="noopener noreferrer">[${s.ref+1}] ${l.refs[s.ref].title} ↗</a></section>`).join('')}${lessonExtras(l)}${l.calculator?`<section class="calculator"><h2>試算看看：風改變了什麼？</h2><p class="muted">僅示範正頂風／順風。頂風填正值，順風填負值。</p><div class="calc-fields"><label>真空速（kt）<input id="tas" type="number" value="100" min="1" max="1000"></label><label>頂風（kt）<input id="wind" type="number" value="20" min="-500" max="500"></label><label>距離（NM）<input id="distance" type="number" value="60" min="0.1" max="10000"></label></div><output id="calc-result" aria-live="polite"></output></section>`:''}<section id="lesson-sources" class="article-sources"><h2>官方來源與版本</h2><p class="muted">以下列出本文參考文件。整理與查閱日期不等於法規生效日；本文不提供完整證照考綱或個人資格判定。</p>${l.refs.map((r,i)=>`<div class="source-card"><a href="${r.url}" target="_blank" rel="noopener noreferrer">[${i+1}] ${r.title} ↗</a><p class="muted">章節：${r.section}<br>版本：${r.version}<br>查閱日期：${r.checked}</p></div>`).join('')}</section><div class="lesson-end"><h2>把剛讀到的知識，留在腦海裡。</h2><div class="quiz-actions"><button class="button secondary" data-read="${l.id}" aria-pressed="${saved.read.includes(l.id)}">${saved.read.includes(l.id)?'✓ 已讀完（取消標記）':'標記為已讀'}</button>${l.questionIds.length?`<button class="button" data-lesson-quiz="${l.id}">章末練習 · ${l.questionIds.length} 題 →</button>`:'<span class="muted">本章可先完成文中的紙上練習</span>'}</div></div></article></div>`;if(l.calculator)calculate();}
function filterLessons(){const t=$('#lesson-track').value,subject=$('#lesson-subject').value,q=$('#lesson-search').value.trim().toLowerCase();const items=lessons.filter(l=>(t==='all'||l.track===t||(t!=='COMMON'&&l.track==='COMMON'))&&(subject==='all'||l.subject===subject)&&(l.title+l.summary+l.subject+l.terms.join(' ')+l.sections.map(s=>s.text).join(' ')).toLowerCase().includes(q));$('#lesson-count').textContent=`共 ${items.length} 篇教材`;$('#lesson-grid').innerHTML=items.length?lessonCards(items):'<div class="empty"><h2>沒有符合的文章</h2><p class="muted">請更換體系或搜尋關鍵字。</p></div>';}
function calculate(){const ids=['tas','wind','distance'];if(ids.some(id=>!$('#'+id).value||!$('#'+id).validity.valid)){$('#calc-result').textContent='請填入範圍內的有效數值。';return;}const gs=Number($('#tas').value)-Number($('#wind').value);$('#calc-result').textContent=gs>0?`地速 ${gs.toFixed(1)} kt · 所需時間 ${(Number($('#distance').value)/gs*60).toFixed(1)} 分鐘`:'地速需大於 0，才能計算此方向的航程時間。';}
app.addEventListener('input',e=>{if(e.target.id==='lesson-search')filterLessons();if(['tas','wind','distance'].includes(e.target.id))calculate();});
app.addEventListener('change',e=>{if(['lesson-track','lesson-subject'].includes(e.target.id))filterLessons();});

function lessonExtras(l){return `${l.table?`<section class="lesson-table"><h2>把資訊放在一起看</h2><div class="table-scroll" role="region" aria-label="${l.title} 對照表" tabindex="0"><table><thead><tr>${l.table.headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${l.table.rows.map(row=>`<tr>${row.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="muted">本站依本章來源整理；數值例題為自編教學情境。</p></section>`:''}${l.misconception?`<section class="misconception"><div class="eyebrow">COMMON MISCONCEPTION</div><h2>這個想法，少了什麼？</h2><p class="myth-claim">「${l.misconception.claim}」</p><p>${l.misconception.correction}</p></section>`:''}${l.selfCheck?`<section class="self-check"><div class="eyebrow">PAUSE & EXPLAIN</div><h2>先用自己的話回答</h2><p>${l.selfCheck.question}</p><details><summary>展開參考答案</summary><p>${l.selfCheck.answer}</p></details><p class="muted">口頭解釋後再比對答案；下方章末練習會另行記錄答題結果。</p></section>`:''}`;}
