import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {lessons} from './lessons.js';
import {tracks,sources,questions,pool,score} from './data.js';
test('every article has substantial text, valid citations and working quiz references',()=>{assert.equal(new Set(lessons.map(l=>l.id)).size,lessons.length);for(const l of lessons){assert.ok(l.sections.length>=3);assert.ok(l.sections.every(s=>s.text.length>70&&l.refs[s.ref]));assert.ok(l.refs.every(r=>new URL(r.url).protocol==='https:'&&r.version&&r.checked));assert.ok(l.questionIds.every(id=>questions.some(q=>q.id===id)));}});
function environment(hash,existing){const elements=new Map(),events={};const element=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',value:'',validity:{valid:true},addEventListener:(type,fn)=>{events['app:'+type]=fn;},insertAdjacentHTML(){}});return elements.get(id);};let stored=existing;const context={lessons,tracks,sources,questions,pool,score,document:{querySelector:element,querySelectorAll:()=>[],addEventListener:(type,fn)=>{events[type]=fn;}},location:{hash},localStorage:{getItem:()=>stored,setItem:(key,value)=>{stored=value;}},window:{addEventListener:(type,fn)=>{events[type]=fn;},scrollTo(){}},setInterval:()=>1,clearInterval(){},console};vm.createContext(context);vm.runInContext(readFileSync('app.js','utf8').replace(/^import .*;$/gm,''),context);return {context,element,events,stored:()=>JSON.parse(stored)};}
test('article routes render sources; old quiz history survives read-progress migration',()=>{const old=JSON.stringify({track:'FAA',attempts:[{id:'i1',correct:true}],wrong:[]});const env=environment('#lesson/angle-of-attack',old);assert.match(env.element('#app').innerHTML,/官方來源與版本/);assert.equal(env.stored().attempts.length,1);env.events.click({target:{closest:()=>({dataset:{read:'angle-of-attack'}})}});assert.deepEqual(env.stored().read,['angle-of-attack']);const reload=environment('#learn',JSON.stringify(env.stored()));assert.match(reload.element('#app').innerHTML,/已讀 1 \/ 6/);});
test('article quiz launches matching questions and unknown article has recovery link',()=>{const env=environment('#lesson/angle-of-attack');env.events.click({target:{closest:()=>({dataset:{lessonQuiz:'angle-of-attack'}})}});assert.match(env.element('#app').innerHTML,/迎角（Angle of attack）/);assert.match(environment('#lesson/missing').element('#app').innerHTML,/返回學習教室/);});
test('navigation calculator handles example and nonpositive groundspeed',()=>{const env=environment('#learn');for(const [id,value] of [['tas','100'],['wind','20'],['distance','60']])env.element('#'+id).value=value;vm.runInContext('calculate()',env.context);assert.match(env.element('#calc-result').textContent,/80.0 kt.*45.0 分鐘/);env.element('#wind').value='100';vm.runInContext('calculate()',env.context);assert.match(env.element('#calc-result').textContent,/地速需大於 0/);});
